mode=dev
ssl=false
host=http://localhost:8090
httpProxy=true
applycommunication=true
webdavCredential=false
webdavHost=
webdavUsername=
webdavPassword=
webdavInsecure=
exporter=ELIOT
exportPath=/tmp
exportDestination=
senderEmail=noreply@entcore.org
neo4jPlugin=false
neo4jUri=http://neo4j:7474
logoutCallback=
dbName=one_gridfs
mongoDbName=one_gridfs
mongoHost=mongo
mongoPort=27017
sqlUrl=jdbc:postgresql://postgres:5432/ong?stringtype=unspecified
modPostgresUrl=jdbc:postgresql://postgres:5432/ong?stringtype=unspecified
sqlUsername=web-education
sqlPassword=We_1234
credentials_postgresql_apps=We_1234
explorerEsUrl=http://elasticsearch:9200
fsStoragePath=/srv/storage/
fsAvatarPath=/srv/storage/avatars/
flatAvatarStorage=false
patternDefaultRegisteredService="^(http|https):\\/\\/.*"
patternUidRegisteredService=
patternUniversalisRegisteredService=
patternLeSiteTvRegisteredService=
patternKneRegisteredService=
patternPronoteRegisteredService=
patternEliotRegisteredService=
patternWebclasseursRegisteredService=
patternProEPSRegisteredService=
patternEducagriRegisteredService=
patternEduMediaRegisteredService=
patternGepiRegisteredService=
patternMSELRegisteredService=
patternGRRRegisteredService=
resourcesApplications="workspace"
widgets=
defaultCommunicationRules=
assetsPath=/srv/springboard
skin=raw
swiftUri=
swiftContainer=
swiftUser=
swiftKey=
passwordRegex=.*
skins={"localhost:8090":"raw"}
activationAutoLogin=false
signKey=
directoryCalendarSwitch=
adminZimbra=
samlMetadataFolder=
samlPrivateKey=
federationLoginUri=
federationCallBackParam=
sharedConf=
samlServicesProviders={}
samlIssuer=
samlSLO=true
autoExport=false
authMandatoryFields={}
federatedAddress={}
activationWelcomeMessage=false
teacherForgotPasswordEmail=false
createdUserEmail=false
classDefaultRoles=false
emailConfig=
bprEnabled=
emailProvider=
cantooOptionalFeatureScriptPath=
restrictCRUDToADMC=
visiblesSearchType=
getVisibleStrategy=
debounceTimeToAutoSave=5000
brokerType=nats
brokerNatsUrl=nats://nats:4222
xitiSwitch=
magnetoWebsocketMaxUsers=5000
magnetoWebsocketMaxUsersPerBoard=500
magnetoWebsocketPort=9092
daysBeforeNotifClosing=1
